# Site settings
title: Aweigh
email:
author: tab tech
description: Aweigh. A travel journal app designed with the traveler in mind to easily capture and share your story.
url: https://aweighapp.com

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
twitter_username:
facebook_username: aweighapp
instagram_username:
# Typography
