# Site settings
title: Story Home
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Share travel stories with those you miss back home.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gifted-brattain-760941.netlify.com" # the base hostname & protocol for your site
twitter_username: 
dribbble_username: 

# Build settings
markdown: kramdown
permalink: pretty
